### ISSUE TITLE
Полет тела по параболе

### ISSUE THREAD

**Issue by Ghoost17** [Ghoost17/WPF2020#2]
Файл parabola, задание по полёту тела по параболе
Мх201 Клюкин Н

**Comment by Ghoost17** [comment]
Файл parabola, задание по полёту тела по параболе
Мх201 Клюкин Н

**Comment by justjune** [comment]
Унылая программа: приглашений к вводу нет, входные данные целые, шаг разбиения для вывода не зависит от времени полета, записи вывода в файл нет.
