### ISSUE TITLE
ДЗ

### ISSUE THREAD

**Issue by Ghoost17** [Ghoost17/WPF2020#3]
Сделал, из первой главы программку которая меняет размер окна. (Chapter1)

**Comment by justjune** [comment]
А без xaml вы сможете аналогичную программу написать?

**Comment by Ghoost17** [comment]
Скорее всего да, просто в студии по стандарту он создает проект в таком виде
Я и делал как есть

**Comment by justjune** [comment]
Попробуйте с пустого проекта С# .NET (а не WPF) для проверки этого утверждения. (Подробности описаны в Главе 1)

**Comment by Ghoost17** [comment]
Сделал 5ю главу из пустого проекта, оказалось не сложнее чем было раньше.

**Comment by justjune** [comment]
Почему должно быть сложнее? Вы просто пока не поняли, как из xaml генерируется C#.

**Comment by Ghoost17** [comment]
UPD: Залил 6 главу

**Comment by justjune** [comment]
40% - за отсутствие комментариев

**Comment by Ghoost17** [comment]
UPD: главы 7,8

**Comment by justjune** [comment]
В главе 8 комментарии до конца не дописаны

**Comment by Ghoost17** [comment]
UPD: + главы 9 и 10

**Comment by Ghoost17** [comment]
UPD: +главы 11 12 13

**Comment by Ghoost17** [comment]
Как удобнее отмечать задания, в одном issue, или создавать новые?

**Comment by justjune** [comment]
Разве главы 11, 12 было нужно делать?
Задания отмечайте, как вам удобнее.

**Comment by justjune** [comment]
Глава 16 - зачем? Тем более, что не рабочая...

**Comment by Ghoost17** [comment]
Я делал программы, как читал учебник, не заметил что их не надо было делать
UPD:+29 глава

**Comment by Ghoost17** [comment]
UPD:   +21 +25

**Comment by Ghoost17** [comment]
До какого числа можно сдавать задания по практике?

**Comment by justjune** [comment]
До даты экзамена

**Comment by justjune** [comment]
Никита, проверьте свою успеваемость - все зачтено?

**Comment by Ghoost17** [comment]
Вроде бы да
